POST http://localhost:3000/api/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImQyNmRmZTgyLWY2NjgtNGY0MS1iMTY1LTkzNGM2ODYyNGU4YiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3lsZXhhdGt1enVubnBjYm9vZGtpLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyNGE3YjA4MC0yOTJlLTQ1YzUtYTQ5Zi1jY2Q2Yjc1MjY2OTgiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgzNDQ0OTA2LCJpYXQiOjE3ODM0NDEzMDYsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzgzNDQxMzA2fV0sInNlc3Npb25faWQiOiI2NTE2ODNjMS02YTBlLTRjOWMtYWQzMy01NzE3YmI5MTZhNTYiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.HljO-4OasSA_0xtC3b_PfnRm9JYmUrZkxQfq9yt-ChXk_bZJWvOheveYQRfqF-FknfgSYfW1GQb4m3EzT_lm8A

{
  "destination_id": "rBdH",
  "hotel_id": "HGOU",
  "start_date": "2025-08-02T10:00:00Z",
  "end_date": "2025-08-06T10:00:00Z",
  "adults": 6,
  "children": 7,
  "room_types": ["ocean"],
  "price_paid": 677,
  "user_id": "24a7b080-292e-45c5-a49f-ccd6b7526698"
}
