POST http://localhost:3000/api/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImQyNmRmZTgyLWY2NjgtNGY0MS1iMTY1LTkzNGM2ODYyNGU4YiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3lsZXhhdGt1enVubnBjYm9vZGtpLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyNGE3YjA4MC0yOTJlLTQ1YzUtYTQ5Zi1jY2Q2Yjc1MjY2OTgiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgzNDQxMjk0LCJpYXQiOjE3ODM0Mzc2OTQsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzgzNDM3Njk0fV0sInNlc3Npb25faWQiOiI2OTM4MjNkYy1lNWFjLTRhYzQtODYxYy05ODUwYjcyMGFlODYiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.jlnscdGqLNWvEU-huFIiOylUI7v54cuDOJCO20jnMiaYaVebE3rc4VlVc6Lhgo3_Hebbfn8sw-TgFevQVxxg3w

{
  "destination_id": "rBdH",
  "hotel_id": "HGOU",
  "start_date": "2025-08-02T10:00:00Z",
  "end_date": "2025-08-06T10:00:00Z",
  "adults": 6,
  "children": 7,
  "room_types": ["ocean"],
  "price_paid": 677,
  "user_id": "24a7b080-292e-45c5-a49f-ccd6b7526698"
}
