/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelsIndexRouteImport } from './routes/hotels/index'
import { Route as HotelsHotelIdRouteImport } from './routes/hotels/$hotelId'
import { Route as AuthenticatedConfirmationRouteImport } from './routes/_authenticated/confirmation'
import { Route as AuthenticatedBookingRouteImport } from './routes/_authenticated/booking'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsHotelIdRoute = HotelsHotelIdRouteImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfirmationRoute =
  AuthenticatedConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookingRoute = AuthenticatedBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/booking': typeof AuthenticatedBookingRoute
  '/confirmation': typeof AuthenticatedConfirmationRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/hotels/': typeof HotelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/booking': typeof AuthenticatedBookingRoute
  '/confirmation': typeof AuthenticatedConfirmationRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/hotels': typeof HotelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/booking': typeof AuthenticatedBookingRoute
  '/_authenticated/confirmation': typeof AuthenticatedConfirmationRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/hotels/': typeof HotelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/booking'
    | '/confirmation'
    | '/hotels/$hotelId'
    | '/hotels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/booking'
    | '/confirmation'
    | '/hotels/$hotelId'
    | '/hotels'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/booking'
    | '/_authenticated/confirmation'
    | '/hotels/$hotelId'
    | '/hotels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  HotelsHotelIdRoute: typeof HotelsHotelIdRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/confirmation': {
      id: '/_authenticated/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof AuthenticatedConfirmationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/booking': {
      id: '/_authenticated/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof AuthenticatedBookingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBookingRoute: typeof AuthenticatedBookingRoute
  AuthenticatedConfirmationRoute: typeof AuthenticatedConfirmationRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBookingRoute: AuthenticatedBookingRoute,
  AuthenticatedConfirmationRoute: AuthenticatedConfirmationRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  HotelsHotelIdRoute: HotelsHotelIdRoute,
  HotelsIndexRoute: HotelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
